-- seed.sql — sample data for the Wenger B2B content calendar.
-- Generated by scripts/gen-seed.mjs from reference/ContentTracker.jsx.
-- Idempotent: safe to re-run (truncates first).

truncate table events, campaigns, initiatives, brands restart identity cascade;

-- brands (7)
insert into brands (id, label, dot, tint, text) values
  ('wenger', 'Wenger', '#1C3B66', '#dfe4ea', '#0e1e33'),
  ('jrclancy', 'JRClancy', '#2E6B3E', '#e2eae4', '#17361f'),
  ('gearboss', 'GearBoss', '#B22234', '#f4e0e3', '#59111a'),
  ('cc', 'Creative Conners', '#E0721F', '#fbebe0', '#703910'),
  ('txscenic', 'Texas Scenic', '#3E5871', '#e4e8eb', '#1f2c39'),
  ('lutefish', 'Lutefish', '#0E7C86', '#ddedee', '#073e43'),
  ('corp', 'Corporate', '#4A5568', '#e6e7ea', '#252b34');

-- initiatives (7)
insert into initiatives (id, name, owner, status) values
  ('11111111-1111-1111-1111-111111111101', 'Prop 28', 'Whitney Winkels', 'In flight'),
  ('11111111-1111-1111-1111-111111111102', 'TX Friday Night Ready', 'Mark Mireles', 'Launching soon'),
  ('11111111-1111-1111-1111-111111111103', 'GearBoss athletics push', 'Pete Veal', 'On track'),
  ('11111111-1111-1111-1111-111111111104', 'JRClancy rigging spotlight', 'Whitney Winkels', 'In review'),
  ('11111111-1111-1111-1111-111111111105', 'Creative Conners Spikemark', 'Unassigned', 'Planning'),
  ('11111111-1111-1111-1111-111111111106', 'PUPN facilities feature', 'Mark Mireles', 'On track'),
  ('11111111-1111-1111-1111-111111111107', 'Texas Scenic search', 'Mark Mireles', 'On track');

-- campaigns (8)
insert into campaigns (id, initiative_id, brand_id, name, channel, vendor, segment, owner, sf_code, utm_source, utm_medium, utm_content, leads, pipeline) values
  ('22222222-2222-2222-2222-222222222201', '11111111-1111-1111-1111-111111111101', 'wenger', 'Prop 28 — email waves', 'Email', 'N/A (Owned)', 'Elementary; Secondary; Purchasing', 'Whitney Winkels', 'WEN-2026-PROP28', 'email', 'email', 'wave4-urgency', 142, 86000),
  ('22222222-2222-2222-2222-222222222202', '11111111-1111-1111-1111-111111111102', 'corp', 'TXFN — weekly email', 'Email', 'N/A (Owned)', 'TX K-12 Athletics', 'Mark Mireles', 'CORP-2026-TXFN-EML', 'email', 'email', 'wave1-urgency', 0, 0),
  ('22222222-2222-2222-2222-222222222203', '11111111-1111-1111-1111-111111111103', 'gearboss', 'AirPro Elite banner', 'Banner Ads', 'LinkedIn', 'Athletic Directors', 'Pete Veal', 'GB-2026-ATH', 'linkedin', 'display', 'airpro-elite', 58, 41000),
  ('22222222-2222-2222-2222-222222222204', '11111111-1111-1111-1111-111111111104', 'jrclancy', 'Rigging spotlight email', 'Email Sponsorship', 'SBO', 'Theatre Facilities', 'Whitney Winkels', 'JRC-2026-RIG', 'sbo', 'email', 'rigging-spotlight', 23, 19000),
  ('22222222-2222-2222-2222-222222222205', '11111111-1111-1111-1111-111111111105', 'cc', 'Spikemark control demo', 'Webinar', 'Direct', 'Production Managers', 'Unassigned', 'CCN-2026-SPK', 'webinar', 'event', 'spikemark-demo', 0, 0),
  ('22222222-2222-2222-2222-222222222206', '11111111-1111-1111-1111-111111111106', 'wenger', 'PUPN — Wenger feature', 'Email Sponsorship', 'PUPN', 'Facilities Directors', 'Mark Mireles', 'WEN-2026-PUPN', 'pupn', 'email', 'facilities-wenger', 19, 14000),
  ('22222222-2222-2222-2222-222222222207', '11111111-1111-1111-1111-111111111106', 'gearboss', 'PUPN — GearBoss feature', 'Email Sponsorship', 'PUPN', 'Athletic Facilities', 'Pete Veal', 'GB-2026-PUPN', 'pupn', 'email', 'facilities-gearboss', 12, 9000),
  ('22222222-2222-2222-2222-222222222208', '11111111-1111-1111-1111-111111111107', 'txscenic', 'Stage systems search', 'Search Ads', 'Google', 'Higher Ed Theatre', 'Mark Mireles', 'TXS-2026-SRCH', 'google', 'cpc', 'stage-systems', 31, 22000);

-- events (28)
insert into events (campaign_id, type, date, label) values
  ('22222222-2222-2222-2222-222222222201', 'comp', '2026-05-08', 'W1 comp'),
  ('22222222-2222-2222-2222-222222222201', 'launch', '2026-05-13', 'Prop 28 W1'),
  ('22222222-2222-2222-2222-222222222201', 'launch', '2026-05-20', 'Prop 28 W2'),
  ('22222222-2222-2222-2222-222222222201', 'launch', '2026-05-27', 'Prop 28 W3'),
  ('22222222-2222-2222-2222-222222222201', 'comp', '2026-06-05', 'W4 comp'),
  ('22222222-2222-2222-2222-222222222201', 'launch', '2026-06-10', 'Prop 28 W4'),
  ('22222222-2222-2222-2222-222222222201', 'launch', '2026-06-17', 'Prop 28 W5'),
  ('22222222-2222-2222-2222-222222222201', 'launch', '2026-06-24', 'Prop 28 W6'),
  ('22222222-2222-2222-2222-222222222201', 'launch', '2026-07-01', 'Prop 28 W7'),
  ('22222222-2222-2222-2222-222222222201', 'launch', '2026-07-08', 'Prop 28 W8'),
  ('22222222-2222-2222-2222-222222222202', 'comp', '2026-06-12', 'TXFN review'),
  ('22222222-2222-2222-2222-222222222202', 'launch', '2026-06-19', 'TXFN wk1'),
  ('22222222-2222-2222-2222-222222222202', 'launch', '2026-06-26', 'TXFN wk2'),
  ('22222222-2222-2222-2222-222222222202', 'launch', '2026-07-03', 'TXFN wk3'),
  ('22222222-2222-2222-2222-222222222202', 'launch', '2026-07-10', 'TXFN wk4'),
  ('22222222-2222-2222-2222-222222222203', 'comp', '2026-06-10', 'GB comp'),
  ('22222222-2222-2222-2222-222222222203', 'launch', '2026-06-17', 'GB banner'),
  ('22222222-2222-2222-2222-222222222203', 'launch', '2026-07-15', 'GB refresh'),
  ('22222222-2222-2222-2222-222222222204', 'comp', '2026-06-18', 'JRClancy comp'),
  ('22222222-2222-2222-2222-222222222204', 'launch', '2026-06-24', 'Rigging email'),
  ('22222222-2222-2222-2222-222222222205', 'comp', '2026-06-13', 'Spikemark comp'),
  ('22222222-2222-2222-2222-222222222205', 'launch', '2026-06-22', 'Spikemark'),
  ('22222222-2222-2222-2222-222222222206', 'comp', '2026-06-15', 'PUPN-W comp'),
  ('22222222-2222-2222-2222-222222222206', 'launch', '2026-06-29', 'PUPN Wenger'),
  ('22222222-2222-2222-2222-222222222207', 'comp', '2026-06-16', 'PUPN-G comp'),
  ('22222222-2222-2222-2222-222222222207', 'launch', '2026-07-06', 'PUPN GearBoss'),
  ('22222222-2222-2222-2222-222222222208', 'launch', '2026-05-21', 'TXS search'),
  ('22222222-2222-2222-2222-222222222208', 'launch', '2026-07-09', 'TXS search');
